sonar.tests=packages/cli/test,packages/rimworld/test
sonar.coverage.exclusions=packages/*/test/**,packages/*/dist/**,packages/cli/scripts/**

sonar.issue.ignore.multicriteria=awaitInLoop,todoMarker,ansiRegex,actionTag

sonar.issue.ignore.multicriteria.awaitInLoop.ruleKey=typescript:S9382
sonar.issue.ignore.multicriteria.awaitInLoop.resourceKey=**/*.ts

sonar.issue.ignore.multicriteria.todoMarker.ruleKey=*:S1135
sonar.issue.ignore.multicriteria.todoMarker.resourceKey=**/*

sonar.issue.ignore.multicriteria.ansiRegex.ruleKey=typescript:S6325
sonar.issue.ignore.multicriteria.ansiRegex.resourceKey=**/cli/logpane.ts

sonar.issue.ignore.multicriteria.actionTag.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.actionTag.resourceKey=**/.github/workflows/**
