sonar.issue.ignore.multicriteria=awaitInLoop,todoMarker,ansiRegex

sonar.issue.ignore.multicriteria.awaitInLoop.ruleKey=typescript:S9382
sonar.issue.ignore.multicriteria.awaitInLoop.resourceKey=**/*.ts

sonar.issue.ignore.multicriteria.todoMarker.ruleKey=*:S1135
sonar.issue.ignore.multicriteria.todoMarker.resourceKey=**/*

sonar.issue.ignore.multicriteria.ansiRegex.ruleKey=typescript:S6325
sonar.issue.ignore.multicriteria.ansiRegex.resourceKey=**/cli/logpane.ts
